repos:
  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.14.3
    hooks:
      - id: ruff
        args: ["--config=pyproject.toml"]

  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        name: Check YAML
        entry: check-yaml
        args: ["--allow-multiple-documents", "--unsafe"]
      - id: check-added-large-files
        exclude: "^docs/assets/"
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml

  - repo: git@github.com:psf/black.git
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--config=pyproject.toml"]

  - repo: local
    hooks:
      - id: prevent-mkdocs-yml-change
        name: Prevent committing modified mkdocs.yml
        entry: bash -c 'git diff --cached --name-only | grep -q "^mkdocs.yml$" && { echo "‚ùå mkdocs.yml changes are not allowed to be committed!"; exit 1; } || exit 0'
        language: system
        types: [file]

  - repo: local
    hooks:
      - id: order-class-members
        name: Reorder class members automatically (Google Style)
        entry: poetry run python scripts/order_members.py
        language: system
        types: [python]
        pass_filenames: true
